### ISSUE TITLE
Ler arquivos xml usando a lib

### ISSUE THREAD

**Issue by candinho-silveira** [Unimake/DFe#1]
Ols, nao consigo ler arquivos xml com a lib, gera o erro `System.Exception: 'There is an error in XML document (1, 40).<nfeProc xmlns='http://www.portalfiscal.inf.br/nfe'> was not expected.'`
` [ObservableProperty]
        private ObservableCollection<NFe> notas;

        [RelayCommand]
        private async Task SelecionarPasta()
        {
            Notas ??= new();
            var dialog = new OpenFileDialog();
            dialog.Filter = "Arquivos XML (*.xml)|*.xml";
            dialog.Multiselect = true;

            if (dialog.ShowDialog() == true)
            {
                string folderPath = Path.GetDirectoryName(dialog.FileName);
                List<string> xmlFiles = Directory.GetFiles(folderPath, "*.xml", SearchOption.AllDirectories).ToList();
                foreach(var xml in xmlFiles)
                {
                    NFe nfe = new();
                    nfe.LoadFromXML(File.ReadAllText(xml));
                   
                   
                    Notas.Add(nfe);
                   
                    string teste = "";
                }
               
            }
        }
    }`

**Comment by candinho-silveira** [comment]
tentei assim tambem com mesmo erro:
` [ObservableProperty]
        private ObservableCollection<NfeProc> notas;

        [RelayCommand]
        private async Task SelecionarPasta()
        {
            Notas ??= new();
            var dialog = new OpenFileDialog();
            dialog.Filter = "Arquivos XML (*.xml)|*.xml";
            dialog.Multiselect = true;

            if (dialog.ShowDialog() == true)
            {
                string folderPath = Path.GetDirectoryName(dialog.FileName);
                List<string> xmlFiles = Directory.GetFiles(folderPath, "*.xml", SearchOption.AllDirectories).ToList();
                foreach(var xml in xmlFiles)
                {
                    NfeProc nfe = new();
                    nfe.LoadFromFile(xml);
                  
                   
                    Notas.Add(nfe);
                   
                    string teste = "";
                }
               
            }
        }
    }`

**Comment by wandreymundin** [comment]
Preciso ver o XML que vc está tentando fazer a leitura para poder orientar. Envie o XML que analiso e te dou um retorno.

**Comment by candinho-silveira** [comment]
Opa, consegui resolver, o erro ocorria devido a um xml da pasta nao ter o nfeproc, apenas o nfe, por isso que gerava o erro
para resolver tive que pegar todos os xml e verificar o elemento root, com isso separei o diferente e depois criei o nfe direto com este xml sem o proc, e instanciei um novo nfeproc e vinculei o nfe

**Comment by wandreymundin** [comment]
Maravilha!!!

Se precisar de algo urgente é mais rápido me encontrar no TELEGRAM, só me procurar por lá:
https://t.me/wandreymundin

**Comment by wandreymundin** [comment]
Resolvido, conforme comentários acima.
